import{a as q,S as O,i as M}from"./assets/vendor-Db2TdIkw.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const P="49660989-ba495770243477578b97293ac",m=async(r,e)=>{const s=new URLSearchParams({key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15});return await q(`https://pixabay.com/api/?${s}`)},f=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more-btn");let x=new O(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});const g=r=>{const e=r.map(({id:s,largeImageURL:n,webformatURL:t,tags:o,likes:a,views:v,comments:S,downloads:$})=>`
           <a class="gallery-link" href="${n}">
               <div class="gallery-item" id="${s}">
                   <img class="gallery-item-img" src="${t}" alt="${o}" loading="lazy" />
                   <div class="info">
                       <p class="info-item"><b>Likes </b>${a}</p>
                       <p class="info-item"><b>Views </b>${v}</p>
                       <p class="info-item"><b>Comments </b>${S}</p>
                       <p class="info-item"><b>Downloads </b>${$}</p>
                   </div>
               </div>
           </a>
       `).join("");f.insertAdjacentHTML("beforeend",e),x.refresh()},B=()=>{f.innerHTML=""},h=()=>{p.classList.add("show")},b=()=>{p.classList.remove("show")},L=()=>{y.classList.add("load-more-show")},w=()=>{y.classList.remove("load-more-show")};function E(){const r=document.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({left:0,top:e*1,behavior:"smooth"})}}const T=document.querySelector(".form");document.querySelector(".btn-form");const u=document.querySelector(".load-more-btn");let d=1,l="",i=0;T.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),!l){c(),input.focus();return}d=1,i=0,B(),w(),h();try{const{data:e}=await m(l,d),s=e.hits;if(!s.length){c(),input.focus();return}g(s),i+=s.length,i<e.totalHits&&L()}catch{c()}finally{b(),r.target.reset()}});u.addEventListener("click",async r=>{d++,u.disabled=!0,h();try{const{data:e}=await m(l,d),s=e.hits;g(s),E(),i+=s.length,i<e.totalHits?L():w()}catch{c()}finally{b(),u.disabled=!1}});const c=()=>{M.error({position:"topLeft",title:"Error",message:"There was an error fetching the images. Please try again later."})};
//# sourceMappingURL=index.js.map
