import{a as v,S as q,i as l}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const P="49660989-ba495770243477578b97293ac",u=async(o,t)=>{const s=new URLSearchParams({key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15});return await v(`https://pixabay.com/api/?${s}`)},f=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more-btn");let $=new q(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});const g=o=>{const t=o.map(({id:s,largeImageURL:a,webformatURL:e,tags:r,likes:i,views:L,comments:w,downloads:S})=>`
           <a class="gallery-link" href="${a}">
               <div class="gallery-item" id="${s}">
                   <img class="gallery-item-img" src="${e}" alt="${r}" loading="lazy" />
                   <div class="info">
                       <p class="info-item"><b>Likes </b>${i}</p>
                       <p class="info-item"><b>Views </b>${L}</p>
                       <p class="info-item"><b>Comments </b>${w}</p>
                       <p class="info-item"><b>Downloads </b>${S}</p>
                   </div>
               </div>
           </a>
       `).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()},E=()=>{f.innerHTML=""},h=()=>{p.classList.add("show")},d=()=>{p.classList.remove("show")},b=()=>{y.classList.add("load-more-show")},O=()=>{y.classList.remove("load-more-show")};function M(){const o=document.querySelector(".gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({left:0,top:t*1,behavior:"smooth"})}}const x=document.querySelector(".form");document.querySelector(".btn-form");const c=document.querySelector(".load-more-btn");let n=1,m="";x.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.elements["search-text"].value.trim();if(n=1,!t){l.error({position:"topLeft",title:"Error",message:"Please enter a search query!"});return}m=t,h();try{const{data:s}=await u(m,n),a=s.hits;if(d(),E(),a.length===0){l.error({position:"topLeft",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}s.totalHits>a.length&&b(),g(a)}catch{d(),l.error({position:"topLeft",title:"Error",message:"There was an error fetching the images. Please try again later."})}finally{o.target.reset()}});c.addEventListener("click",async o=>{n++,c.disabled=!0,h();try{const{data:t}=await u(m,n),s=t.hits;g(s),M(),t.totalHits>n*15?b():O()}catch{l.error({position:"topLeft",title:"Error",message:"There was an error fetching the images. Please try again later."})}finally{d(),c.disabled=!1}});
//# sourceMappingURL=index.js.map
